#!/bin/bash

echo "🚀 Florida Realtor Platform - One-Click Deployment"
echo "=================================================="
echo ""

FRONTEND_URL="https://frontend-78y7317t7-movshovichs-projects.vercel.app"
GITHUB_REPO="https://github.com/movshovich/florida-realtor-platform"

echo "✅ Frontend already deployed: $FRONTEND_URL"
echo "✅ Code pushed to GitHub: $GITHUB_REPO"
echo ""

echo "📦 Backend Deployment Options:"
echo ""
echo "Option 1: Railway (Recommended)"
echo "  1. Go to: https://railway.app"
echo "  2. Click 'New Project' → 'Deploy from GitHub repo'"
echo "  3. Select: movshovich/florida-realtor-platform"
echo "  4. Set Root Directory: backend"
echo "  5. Add PostgreSQL database (New → Database → PostgreSQL)"
echo "  6. Set environment variables (see below)"
echo "  7. Railway will auto-deploy!"
echo ""

echo "Option 2: Render (Easier)"
echo "  1. Go to: https://render.com"
echo "  2. Click 'New' → 'Web Service'"
echo "  3. Connect GitHub: movshovich/florida-realtor-platform"
echo "  4. Settings:"
echo "     - Root Directory: backend"
echo "     - Build Command: npm install && npx prisma generate"
echo "     - Start Command: npm start"
echo "  5. Add PostgreSQL database"
echo "  6. Set environment variables (see below)"
echo "  7. Deploy!"
echo ""

echo "🔐 Required Environment Variables:"
echo ""
JWT_SECRET=$(openssl rand -base64 32)
echo "JWT_SECRET=$JWT_SECRET"
echo "JWT_EXPIRES_IN=7d"
echo "FRONTEND_URL=$FRONTEND_URL"
echo "NODE_ENV=production"
echo "PORT=3001 (or platform default)"
echo "DATABASE_URL=(automatically set by platform)"
echo ""

echo "📊 After Deployment, Run Migrations:"
echo ""
echo "Railway:"
echo "  railway run npx prisma migrate deploy"
echo "  railway run npm run seed"
echo ""
echo "Render:"
echo "  In Shell: npx prisma migrate deploy"
echo "  In Shell: npm run seed"
echo ""

echo "🌐 Final Step - Update Vercel:"
echo ""
echo "1. Get your backend URL from Railway/Render"
echo "2. Go to: https://vercel.com/movshovichs-projects/frontend/settings/environment-variables"
echo "3. Add: NEXT_PUBLIC_API_URL = your backend URL"
echo "4. Redeploy frontend"
echo ""

echo "✅ That's it! Your app will be live!"
echo ""
echo "📝 Quick Links:"
echo "  - Frontend: $FRONTEND_URL"
echo "  - GitHub: $GITHUB_REPO"
echo "  - Railway: https://railway.app"
echo "  - Render: https://render.com"
echo "  - Vercel: https://vercel.com/movshovichs-projects/frontend"
echo ""

