#!/bin/bash
echo "🚀 Deploying Backend to Render..."
echo "=================================="
echo ""
echo "✅ Code is on GitHub: https://github.com/movshovich/florida-realtor-platform"
echo ""
echo "📝 Next Steps:"
echo "1. Go to: https://dashboard.render.com"
echo "2. Click 'New' → 'Web Service'"
echo "3. Connect GitHub and select: movshovich/florida-realtor-platform"
echo "4. Configure:"
echo "   - Name: florida-realtor-backend"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install && npx prisma generate"
echo "   - Start Command: npm start"
echo "5. Add PostgreSQL database"
echo "6. Set environment variables"
echo "7. Deploy!"
echo ""
echo "🔐 Environment Variables to Set:"
JWT_SECRET=$(openssl rand -base64 32)
echo "JWT_SECRET=$JWT_SECRET"
echo "JWT_EXPIRES_IN=7d"
echo "FRONTEND_URL=https://frontend-78y7317t7-movshovichs-projects.vercel.app"
echo "NODE_ENV=production"
echo "PORT=10000"
echo "DATABASE_URL=(from PostgreSQL service)"
